services:
  db:
    image: postgres:16
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data

  nextcloud:
    image: nextcloud:29
    container_name: nextcloud-app
    restart: unless-stopped
    ports:
      - "${NEXTCLOUD_PORT}:80"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${NEXTCLOUD_DATA_PATH}/html:/var/www/html
      - ${NEXTCLOUD_DATA_PATH}/data:/var/www/html/data
    depends_on:
      - db

#  obsidian:
#    image: ghcr.io/vsrkw/obsidian-web:latest
#    container_name: obsidian-viewer
#    restart: unless-stopped
#    ports:
#      - "${OBSIDIAN_PORT}:80"
#    volumes:
#      - ${OBSIDIAN_VAULT_PATH}:/vault:ro,z
#    environment:
#      - DEFAULT_FILE: index.md
#      - VAULT_NAME: ${OBSIDIAN_VAULT_NAME}

